const demoLeaderboardStudents = [
  {
    email: 'arjun.kumar@demo',
    name: 'Arjun Kumar',
    college: 'IIT Ropar',
    department: 'Computer Science',
    spurtiPoints: 2850,
    currentPhase: 'platinum',
    streak: 24,
  },
  {
    email: 'priya.singh@demo',
    name: 'Priya Singh',
    college: 'IIT Ropar',
    department: 'Data Science',
    spurtiPoints: 2640,
    currentPhase: 'platinum',
    streak: 21,
  },
  {
    email: 'raj.patel@demo',
    name: 'Raj Patel',
    college: 'IIT Ropar',
    department: 'Electronics',
    spurtiPoints: 2520,
    currentPhase: 'gold',
    streak: 18,
  },
  {
    email: 'neha.verma@demo',
    name: 'Neha Verma',
    college: 'IIT Ropar',
    department: 'Computer Science',
    spurtiPoints: 2380,
    currentPhase: 'gold',
    streak: 16,
  },
  {
    email: 'aditya.sharma@demo',
    name: 'Aditya Sharma',
    college: 'IIT Ropar',
    department: 'Mechanical',
    spurtiPoints: 2250,
    currentPhase: 'gold',
    streak: 14,
  },
  {
    email: 'riya.gupta@demo',
    name: 'Riya Gupta',
    college: 'IIT Ropar',
    department: 'Mathematics',
    spurtiPoints: 2140,
    currentPhase: 'silver',
    streak: 13,
  },
  {
    email: 'vikram.singh@demo',
    name: 'Vikram Singh',
    college: 'IIT Ropar',
    department: 'Physics',
    spurtiPoints: 2010,
    currentPhase: 'silver',
    streak: 12,
  },
  {
    email: 'anjali.nair@demo',
    name: 'Anjali Nair',
    college: 'IIT Ropar',
    department: 'Computer Science',
    spurtiPoints: 1920,
    currentPhase: 'silver',
    streak: 12,
  },
  {
    email: 'deepak.roy@demo',
    name: 'Deepak Roy',
    college: 'IIT Ropar',
    department: 'Chemistry',
    spurtiPoints: 1840,
    currentPhase: 'silver',
    streak: 10,
  },
  {
    email: 'sneha.das@demo',
    name: 'Sneha Das',
    college: 'IIT Ropar',
    department: 'Biotechnology',
    spurtiPoints: 1760,
    currentPhase: 'silver',
    streak: 10,
  },
  {
    email: 'rohit.joshi@demo',
    name: 'Rohit Joshi',
    college: 'IIT Ropar',
    department: 'Electrical',
    spurtiPoints: 1680,
    currentPhase: 'bronze',
    streak: 8,
  },
  {
    email: 'divya.sharma@demo',
    name: 'Divya Sharma',
    college: 'IIT Ropar',
    department: 'Computer Science',
    spurtiPoints: 1590,
    currentPhase: 'bronze',
    streak: 7,
  },
];

const publicLeaderboardFallback = demoLeaderboardStudents.map((student, index) => ({
  rank: index + 1,
  name: student.name,
  college: student.college,
  totalSp: student.spurtiPoints,
  periodSp: 0,
  phase: student.currentPhase,
  streak: student.streak,
}));

module.exports = {
  demoLeaderboardStudents,
  publicLeaderboardFallback,
};
